replicaCount: 1

image:
  typebotBuilder: "baptistearno/typebot-builder:latest"
  typebotViewer: "baptistearno/typebot-viewer:latest"
  postgres: "postgres:14-alpine"

service:
  typebotBuilder:
    type: ClusterIP
    port: 8080
    targetPort: 3000

  typebotViewer:
    type: ClusterIP
    port: 8081
    targetPort: 3000

env:
  ENCRYPTION_SECRET: "do+UspMmB/rewbX2K/rskFmtgGSSZ8Ta"
  DATABASE_URL: "postgresql://postgres:typebot@typebot-db:5432/typebot"
  NEXTAUTH_URL: ""
  NEXT_PUBLIC_VIEWER_URL: ""
  ADMIN_EMAIL: ""

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 1Gi

resources: {}