apiVersion: apps/v1
kind: Deployment
metadata:
  name: typebot-viewer
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: typebot-viewer
  template:
    metadata:
      labels:
        app: typebot-viewer
    spec:
      containers:
        - name: typebot-viewer
          image: {{ .Values.image.typebotViewer }}
          ports:
            - containerPort: 3000
          env:
            - name: ENCRYPTION_SECRET
              value: {{ .Values.env.ENCRYPTION_SECRET | quote }}
            - name: DATABASE_URL
              value: {{ .Values.env.DATABASE_URL | quote }}
            - name: NEXTAUTH_URL
              value: {{ .Values.env.NEXTAUTH_URL | quote }}
            - name: NEXT_PUBLIC_VIEWER_URL
              value: {{ .Values.env.NEXT_PUBLIC_VIEWER_URL | quote }}
            - name: ADMIN_EMAIL
              value: {{ .Values.env.ADMIN_EMAIL | quote }}
            - name: GOOGLE_CLIENT_ID
              value: {{ .Values.env.GOOGLE_CLIENT_ID | quote }}
            - name: GOOGLE_CLIENT_SECRET
              value: {{ .Values.env.GOOGLE_CLIENT_SECRET | quote }}
            - name: NEXT_PUBLIC_GOOGLE_API_KEY
              value: {{ .Values.env.NEXT_PUBLIC_GOOGLE_API_KEY | quote }}